### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by TargonsD** [Shiroraven/NayuBot#3]
No kind of listener for events such as if a module needs to check messages that are not commands upon being sent, if reactions added to pictures should trigger an event, if an imague upload should trigger an event and so on.

**Comment by TargonsD** [comment]
No communication between modules and events / modules and modules

**Comment by Shiroraven** [comment]
Events can be called within the modules, as the client is passed to every module... run `client.on` to create a listener for a given event and `client.off` when it's no longer in use. 

closing this issue!
